platform :ios, '15.0'

# Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

target 'App' do
  # Firebase pods
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
